### ISSUE TITLE
Example 2: unable to get query response to work

### ISSUE THREAD

**Issue by jonrhythmic** [qicosmos/cinatra#159]
I've been trying to follow the tutorials in Visual Studio 2019 on Windows 10, but when I try query response:  
`localhost:8080/test?name=jon?id=25` 
it returns "no name". Is this a bug, or am I missing something?

I've tested it on both Chrome and Firefox with the same result. Code is identical to the code in example 2: 
```
#include "cinatra.hpp"
using namespace cinatra;

int main() {
	http_server server(std::thread::hardware_concurrency());
	server.listen("0.0.0.0", "8080");
	server.set_http_handler<GET, POST>("/test", [](request& req, response& res) {
		auto name = req.get_header_value("name");
		if (name.empty()) {
			res.set_status_and_content(status_type::bad_request, "no name");
			return;
		}

		auto id = req.get_query_value("id");
		if (id.empty()) {
			res.set_status_and_content(status_type::bad_request);
			return;
		}
		res.set_status_and_content(status_type::ok, "hello world");
	});
	server.run();
	return 0;
}
```

**Comment by qicosmos** [comment]
Actually your queries is not right, using ''localhost:8080/test?name=jon&id=25'',  '?' is just the start character, not allowed in the middle of the query string.

use ''req.get_quey_value("name");'', because the name is not in the head, it's in the query string.

And then you will get the right result.
